services:
  envoy:
    image: envoyproxy/envoy:dev-d69544eec9f285b9fe05548ea18b5f3dc75fb087
    container_name: envoy-container
    ports:
      - "1111:1111"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - envoy-network


  app2222:
    build:
      context: ./servers/server2222
      dockerfile: Dockerfile
    container_name: nest-server2222
    ports:
      - "2222:2222"
    networks:
      - envoy-network

  app3333:
    build:
      context: ./servers/server3333
      dockerfile: Dockerfile
    container_name: nest-server3333
    ports:
      - "3333:3333"
    networks:
      - envoy-network

  app4444:
    build:
      context: ./servers/server4444
      dockerfile: Dockerfile
    container_name: nest-server4444
    ports:
      - "4444:4444"
    networks:
      - envoy-network

  app5555:
    build:
      context: ./servers/server5555
      dockerfile: Dockerfile
    container_name: nest-server5555
    ports:
      - "5555:5555"
    networks:
      - envoy-network

networks:
  envoy-network:
    external: true