services:
  envoy:
    image: envoyproxy/envoy:dev-d69544eec9f285b9fe05548ea18b5f3dc75fb087
    container_name: envoy-container
    ports:
      - "443:443"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - envoy-network


networks:
  envoy-network:
    external: true